# Generated by Django 3.1.6 on 2021-02-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210220_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='photo',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
