# Generated by Django 3.1.6 on 2021-02-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210220_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='dateFinish',
            field=models.DateField(default=None),
        ),
    ]
