# Generated by Django 3.1.6 on 2021-02-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210220_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='dateFinish',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='auction',
            name='dateInsert',
            field=models.DateTimeField(),
        ),
    ]
