# Generated by Django 3.1.6 on 2021-02-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210220_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='currentPrice',
            new_name='initialPrice',
        ),
    ]
