# Generated by Django 3.1.6 on 2021-02-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210220_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='initialPrice',
            new_name='price',
        ),
    ]
